    sv_content_frame.grid_columnconfigure(1, weight=1)
        sv_content_frame.grid_rowconfigure(0, weight=1)

    def create_lop_tab(self):
        lop_main_frame = ttk.Frame(self.tab_lop, style="Main.TFrame")
        lop_main_frame.pack(fill="both", expand=True)
        
        lop_filter_frame = ttk.LabelFrame(lop_main_frame, text="Bộ lọc", padding=10, style="Main.TLabelframe")
        lop_filter_frame.pack(fill="x", padx=10, pady=5)
        ttk.Label(lop_filter_frame, text="Lọc theo Khoa:").pack(side="left", padx=5)
        self.lop_filter_khoa_combo = ttk.Combobox(lop_filter_frame, state="readonly", width=30)
        self.lop_filter_khoa_combo.pack(side="left", padx=5)
        self.lop_filter_khoa_combo.bind("<<ComboboxSelected>>", self.load_lop_data)
        ttk.Button(lop_filter_frame, text=" Bỏ lọc", image=self.clear_filter_icon, compound='left', command=self.clear_lop_filter).pack(side="left", padx=5)

        lop_content_frame = ttk.Frame(lop_main_frame, style="Main.TFrame")
        lop_content_frame.pack(fill="both", expand=True, padx=10, pady=5)
        
        lop_form_frame = ttk.LabelFrame(lop_content_frame, text="Thông tin Lớp", padding=10, style="Main.TLabelframe")
        lop_form_frame.grid(row=0, column=0, rowspan=2, padx=(0,10), sticky="ns")
        ttk.Label(lop_form_frame, text="Tên Lớp:").grid(row=0, column=0, sticky="w", pady=5)
        self.lop_ten_entry = ttk.Entry(lop_form_frame, width=30)
        self.lop_ten_entry.grid(row=0, column=1, sticky="ew", pady=5)
        ttk.Label(lop_form_frame, text="Thuộc Khoa:").grid(row=1, column=0, sticky="w", pady=5)
        self.lop_khoa_combo = ttk.Combobox(lop_form_frame, state="readonly", width=28)
        self.lop_khoa_combo.grid(row=1, column=1, sticky="ew", pady=5)
        
        lop_button_frame = ttk.LabelFrame(lop_form_frame, text="Chức năng", padding=10, style="Main.TLabelframe")
        lop_button_frame.grid(row=2, column=0, columnspan=2, pady=10, sticky="ew")
        ttk.Button(lop_button_frame, text=" Thêm", image=self.add_icon, compound='left', command=self.add_lop).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(lop_button_frame, text=" Cập nhật", image=self.update_icon, compound='left', command=self.update_lop).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(lop_button_frame, text=" Xóa", image=self.delete_icon, compound='left', command=self.delete_lop).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(lop_button_frame, text=" Xóa Form", image=self.clear_icon, compound='left', command=self.clear_lop_form).pack(side="left", expand=True, fill="x", padx=5)
        
        lop_tree_frame = ttk.Frame(lop_content_frame, style="Main.TFrame")
        lop_tree_frame.grid(row=0, column=1, padx=(10,0), sticky="nsew")
        
        self.lop_tree = ttk.Treeview(lop_tree_frame, columns=("ID", "TenLop", "TenKhoa"), show="headings")
        self.lop_tree.heading("ID", text="ID"); self.lop_tree.heading("TenLop", text="Tên Lớp"); self.lop_tree.heading("TenKhoa", text="Tên Khoa")
        self.lop_tree.column("ID", width=50, anchor="center"); self.lop_tree.column("TenLop", width=200); self.lop_tree.column("TenKhoa", width=250)
        
        scrollbar_lop = ttk.Scrollbar(lop_tree_frame, orient="vertical", command=self.lop_tree.yview)
        self.lop_tree.configure(yscrollcommand=scrollbar_lop.set)
        self.lop_tree.pack(side="left", fill="both", expand=True)
        scrollbar_lop.pack(side="right", fill="y")
        self.lop_tree.bind("<<TreeviewSelect>>", self.on_lop_select)
        
        lop_content_frame.grid_columnconfigure(1, weight=1)
        lop_content_frame.grid_rowconfigure(0, weight=1)

    def create_khoa_tab(self):
        khoa_main_frame = ttk.Frame(self.tab_khoa, style="Main.TFrame")
        khoa_main_frame.pack(fill="both", expand=True)
        khoa_form_frame = ttk.LabelFrame(khoa_main_frame, text="Thông tin Khoa", padding=10, style="Main.TLabelframe")
        khoa_form_frame.grid(row=0, column=0, rowspan=2, padx=10, pady=10, sticky="ns")
        ttk.Label(khoa_form_frame, text="Tên Khoa:").grid(row=0, column=0, sticky="w", pady=5)
        self.khoa_ten_entry = ttk.Entry(khoa_form_frame, width=30)
        self.khoa_ten_entry.grid(row=0, column=1, sticky="ew", pady=5)
        khoa_button_frame = ttk.LabelFrame(khoa_form_frame, text="Chức năng", padding=10, style="Main.TLabelframe")
        khoa_button_frame.grid(row=1, column=0, columnspan=2, pady=10, sticky="ew")
        ttk.Button(khoa_button_frame, text=" Thêm", image=self.add_icon, compound='left', command=self.add_khoa).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(khoa_button_frame, text=" Cập nhật", image=self.update_icon, compound='left', command=self.update_khoa).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(khoa_button_frame, text=" Xóa", image=self.delete_icon, compound='left', command=self.delete_khoa).pack(side="left", expand=True, fill="x", padx=5)
        ttk.Button(khoa_button_frame, text=" Xóa Form", image=self.clear_icon, compound='left', command=self.clear_khoa_form).pack(side="left", expand=True, fill="x", padx=5)
        khoa_tree_frame = ttk.Frame(khoa_main_frame, style="Main.TFrame")
        khoa_tree_frame.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")
        self.khoa_tree = ttk.Treeview(khoa_tree_frame, columns=("ID", "TenKhoa"), show="headings")
        self.khoa_tree.heading("ID", text="ID"); self.khoa_tree.heading("TenKhoa", text="Tên Khoa")
        self.khoa_tree.column("ID", width=50, anchor="center"); self.khoa_tree.column("TenKhoa", width=400)
        scrollbar_khoa = ttk.Scrollbar(khoa_tree_frame, orient="vertical", command=self.khoa_tree.yview)
        self.khoa_tree.configure(yscrollcommand=scrollbar_khoa.set)
        self.khoa_tree.pack(side="left", fill="both", expand=True)
        scrollbar_khoa.pack(side="right", fill="y")
        self.khoa_tree.bind("<<TreeviewSelect>>", self.on_khoa_select)
        khoa_main_frame.grid_columnconfigure(1, weight=1)
        khoa_main_frame.grid_rowconfigure(0, weight=1)

    def create_mon_hoc_tab(self):
        mh_main_frame = ttk.Frame(self.tab_mon_hoc, style="Main.TFrame")
        mh_main_frame.pack(fill="both", expand=True)
        mh_form_frame = ttk.LabelFrame(mh_main_frame, text="Thông tin Môn học", padding=10, style="Main.TLabelframe")
        mh_form_frame.grid(row=0, column=0, rowspan=2, padx=10, pady=10, sticky="ns")
        ttk.Label(mh_form_frame, text="Tên Môn học:").grid(row=0, column=0, sticky="w", pady=5)
        self.mh_ten_entry = ttk.Entry(mh_form_frame, width=30)
        self.mh_ten_entry.grid(row=0, column=1, sticky="ew", pady=5)
        ttk.Label(mh_form_frame, text="Số tín chỉ:").grid(row=1, column=0, sticky="w", pady=5)
        self.mh_tin_chi_entry = ttk.Entry(mh_form_frame, width=30)
        self.mh_tin_chi_entry.grid(row=1, column=1, sticky="ew", pady=5)
        ttk.Label(mh_form_frame, text="Thuộc Khoa:").grid(row=2, column=0, sticky="w", pady=5)
        self.mh_khoa_combo = ttk.Combobox(mh_form_frame, state="readonly", width=28)
        self.mh_khoa_combo.grid(row=2, column=1, sticky="ew", pady=5)
        mh_button_frame = ttk.LabelFrame(mh_form_frame, text="Chức năng", padding=10, style="Main.TLabelframe")
        mh_button_frame.grid(row=3, column=0, columnspan=2, pady=10, sticky="ew")
        ttk.Button(mh_button_frame, text=" Thêm", image=self.add_icon, compound='left', command=self.add_mon_hoc).pack(side="left", expand=True, fill="x", padx=5)
        mh_tree_frame = ttk.Frame(mh_main_frame, style="Main.TFrame")
        mh_tree_frame.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")
        self.mh_tree = ttk.Treeview(mh_tree_frame, columns=("ID", "TenMon", "SoTinChi", "TenKhoa"), show="headings")
        self.mh_tree.heading("ID", text="ID"); self.mh_tree.heading("TenMon", text="Tên Môn học"); self.mh_tree.heading("SoTinChi", text="Tín chỉ"); self.mh_tree.heading("TenKhoa", text="Tên Khoa")
        self.mh_tree.column("ID", width=50, anchor="center"); self.mh_tree.column("TenMon", width=250); self.mh_tree.column("SoTinChi", width=60, anchor="center"); self.mh_tree.column("TenKhoa", width=200)
        scrollbar_mh = ttk.Scrollbar(mh_tree_frame, orient="vertical", command=self.mh_tree.yview)
        self.mh_tree.configure(yscrollcommand=scrollbar_mh.set)
        self.mh_tree.pack(side="left", fill="both", expand=True)
